/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAdministracaoRouteImport } from './routes/app/administracao'
import { Route as AppAgendaRouteImport } from './routes/app/agenda'
import { Route as AppDocumentosRouteImport } from './routes/app/documentos'
import { Route as AppEquipeRouteImport } from './routes/app/equipe'
import { Route as AppFinanceiroRouteImport } from './routes/app/financeiro'
import { Route as AppPessoasRouteImport } from './routes/app/pessoas'
import { Route as AppProjetosRouteImport } from './routes/app/projetos'
import { Route as AppUnidadesRouteImport } from './routes/app/unidades'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppEquipeIndexRouteImport } from './routes/app/equipe/index'
import { Route as AppEquipeMemberIdRouteImport } from './routes/app/equipe/$memberId'
import { Route as AppPessoasIndexRouteImport } from './routes/app/pessoas/index'
import { Route as AppPessoasPersonIdRouteImport } from './routes/app/pessoas/$personId'
import { Route as AppProjetosIndexRouteImport } from './routes/app/projetos/index'
import { Route as AppProjetosProjectIdRouteImport } from './routes/app/projetos/$projectId'
import { Route as AppUnidadesIndexRouteImport } from './routes/app/unidades/index'
import { Route as AppUnidadesUnitIdRouteImport } from './routes/app/unidades/$unitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministracaoRoute = AppAdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppEquipeRoute = AppEquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppPessoasRoute = AppPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosRoute = AppProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppUnidadesRoute = AppUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppEquipeIndexRoute = AppEquipeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppEquipeRoute,
} as any)
const AppEquipeMemberIdRoute = AppEquipeMemberIdRouteImport.update({
  id: '/$memberId',
  path: '/$memberId',
  getParentRoute: () => AppEquipeRoute,
} as any)
const AppPessoasIndexRoute = AppPessoasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPessoasRoute,
} as any)
const AppPessoasPersonIdRoute = AppPessoasPersonIdRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => AppPessoasRoute,
} as any)
const AppProjetosIndexRoute = AppProjetosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjetosRoute,
} as any)
const AppProjetosProjectIdRoute = AppProjetosProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjetosRoute,
} as any)
const AppUnidadesIndexRoute = AppUnidadesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppUnidadesRoute,
} as any)
const AppUnidadesUnitIdRoute = AppUnidadesUnitIdRouteImport.update({
  id: '/$unitId',
  path: '/$unitId',
  getParentRoute: () => AppUnidadesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/administracao': typeof AppAdministracaoRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/equipe': typeof AppEquipeRouteWithChildren
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/pessoas': typeof AppPessoasRouteWithChildren
  '/app/projetos': typeof AppProjetosRouteWithChildren
  '/app/unidades': typeof AppUnidadesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/equipe/$memberId': typeof AppEquipeMemberIdRoute
  '/app/pessoas/$personId': typeof AppPessoasPersonIdRoute
  '/app/projetos/$projectId': typeof AppProjetosProjectIdRoute
  '/app/unidades/$unitId': typeof AppUnidadesUnitIdRoute
  '/app/equipe/': typeof AppEquipeIndexRoute
  '/app/pessoas/': typeof AppPessoasIndexRoute
  '/app/projetos/': typeof AppProjetosIndexRoute
  '/app/unidades/': typeof AppUnidadesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/administracao': typeof AppAdministracaoRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app': typeof AppIndexRoute
  '/app/equipe/$memberId': typeof AppEquipeMemberIdRoute
  '/app/pessoas/$personId': typeof AppPessoasPersonIdRoute
  '/app/projetos/$projectId': typeof AppProjetosProjectIdRoute
  '/app/unidades/$unitId': typeof AppUnidadesUnitIdRoute
  '/app/equipe': typeof AppEquipeIndexRoute
  '/app/pessoas': typeof AppPessoasIndexRoute
  '/app/projetos': typeof AppProjetosIndexRoute
  '/app/unidades': typeof AppUnidadesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/administracao': typeof AppAdministracaoRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/equipe': typeof AppEquipeRouteWithChildren
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/pessoas': typeof AppPessoasRouteWithChildren
  '/app/projetos': typeof AppProjetosRouteWithChildren
  '/app/unidades': typeof AppUnidadesRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/equipe/$memberId': typeof AppEquipeMemberIdRoute
  '/app/pessoas/$personId': typeof AppPessoasPersonIdRoute
  '/app/projetos/$projectId': typeof AppProjetosProjectIdRoute
  '/app/unidades/$unitId': typeof AppUnidadesUnitIdRoute
  '/app/equipe/': typeof AppEquipeIndexRoute
  '/app/pessoas/': typeof AppPessoasIndexRoute
  '/app/projetos/': typeof AppProjetosIndexRoute
  '/app/unidades/': typeof AppUnidadesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/administracao'
    | '/app/agenda'
    | '/app/documentos'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/pessoas'
    | '/app/projetos'
    | '/app/unidades'
    | '/auth/callback'
    | '/app/'
    | '/app/equipe/$memberId'
    | '/app/pessoas/$personId'
    | '/app/projetos/$projectId'
    | '/app/unidades/$unitId'
    | '/app/equipe/'
    | '/app/pessoas/'
    | '/app/projetos/'
    | '/app/unidades/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/administracao'
    | '/app/agenda'
    | '/app/documentos'
    | '/app/financeiro'
    | '/auth/callback'
    | '/app'
    | '/app/equipe/$memberId'
    | '/app/pessoas/$personId'
    | '/app/projetos/$projectId'
    | '/app/unidades/$unitId'
    | '/app/equipe'
    | '/app/pessoas'
    | '/app/projetos'
    | '/app/unidades'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/administracao'
    | '/app/agenda'
    | '/app/documentos'
    | '/app/equipe'
    | '/app/financeiro'
    | '/app/pessoas'
    | '/app/projetos'
    | '/app/unidades'
    | '/auth/callback'
    | '/app/'
    | '/app/equipe/$memberId'
    | '/app/pessoas/$personId'
    | '/app/projetos/$projectId'
    | '/app/unidades/$unitId'
    | '/app/equipe/'
    | '/app/pessoas/'
    | '/app/projetos/'
    | '/app/unidades/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/administracao': {
      id: '/app/administracao'
      path: '/administracao'
      fullPath: '/app/administracao'
      preLoaderRoute: typeof AppAdministracaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documentos': {
      id: '/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/equipe': {
      id: '/app/equipe'
      path: '/equipe'
      fullPath: '/app/equipe'
      preLoaderRoute: typeof AppEquipeRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pessoas': {
      id: '/app/pessoas'
      path: '/pessoas'
      fullPath: '/app/pessoas'
      preLoaderRoute: typeof AppPessoasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projetos': {
      id: '/app/projetos'
      path: '/projetos'
      fullPath: '/app/projetos'
      preLoaderRoute: typeof AppProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/unidades': {
      id: '/app/unidades'
      path: '/unidades'
      fullPath: '/app/unidades'
      preLoaderRoute: typeof AppUnidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/equipe/': {
      id: '/app/equipe/'
      path: '/'
      fullPath: '/app/equipe/'
      preLoaderRoute: typeof AppEquipeIndexRouteImport
      parentRoute: typeof AppEquipeRoute
    }
    '/app/equipe/$memberId': {
      id: '/app/equipe/$memberId'
      path: '/$memberId'
      fullPath: '/app/equipe/$memberId'
      preLoaderRoute: typeof AppEquipeMemberIdRouteImport
      parentRoute: typeof AppEquipeRoute
    }
    '/app/pessoas/': {
      id: '/app/pessoas/'
      path: '/'
      fullPath: '/app/pessoas/'
      preLoaderRoute: typeof AppPessoasIndexRouteImport
      parentRoute: typeof AppPessoasRoute
    }
    '/app/pessoas/$personId': {
      id: '/app/pessoas/$personId'
      path: '/$personId'
      fullPath: '/app/pessoas/$personId'
      preLoaderRoute: typeof AppPessoasPersonIdRouteImport
      parentRoute: typeof AppPessoasRoute
    }
    '/app/projetos/': {
      id: '/app/projetos/'
      path: '/'
      fullPath: '/app/projetos/'
      preLoaderRoute: typeof AppProjetosIndexRouteImport
      parentRoute: typeof AppProjetosRoute
    }
    '/app/projetos/$projectId': {
      id: '/app/projetos/$projectId'
      path: '/$projectId'
      fullPath: '/app/projetos/$projectId'
      preLoaderRoute: typeof AppProjetosProjectIdRouteImport
      parentRoute: typeof AppProjetosRoute
    }
    '/app/unidades/': {
      id: '/app/unidades/'
      path: '/'
      fullPath: '/app/unidades/'
      preLoaderRoute: typeof AppUnidadesIndexRouteImport
      parentRoute: typeof AppUnidadesRoute
    }
    '/app/unidades/$unitId': {
      id: '/app/unidades/$unitId'
      path: '/$unitId'
      fullPath: '/app/unidades/$unitId'
      preLoaderRoute: typeof AppUnidadesUnitIdRouteImport
      parentRoute: typeof AppUnidadesRoute
    }
  }
}

interface AppEquipeRouteChildren {
  AppEquipeMemberIdRoute: typeof AppEquipeMemberIdRoute
  AppEquipeIndexRoute: typeof AppEquipeIndexRoute
}

const AppEquipeRouteChildren: AppEquipeRouteChildren = {
  AppEquipeMemberIdRoute: AppEquipeMemberIdRoute,
  AppEquipeIndexRoute: AppEquipeIndexRoute,
}

const AppEquipeRouteWithChildren = AppEquipeRoute._addFileChildren(
  AppEquipeRouteChildren,
)

interface AppPessoasRouteChildren {
  AppPessoasPersonIdRoute: typeof AppPessoasPersonIdRoute
  AppPessoasIndexRoute: typeof AppPessoasIndexRoute
}

const AppPessoasRouteChildren: AppPessoasRouteChildren = {
  AppPessoasPersonIdRoute: AppPessoasPersonIdRoute,
  AppPessoasIndexRoute: AppPessoasIndexRoute,
}

const AppPessoasRouteWithChildren = AppPessoasRoute._addFileChildren(
  AppPessoasRouteChildren,
)

interface AppProjetosRouteChildren {
  AppProjetosProjectIdRoute: typeof AppProjetosProjectIdRoute
  AppProjetosIndexRoute: typeof AppProjetosIndexRoute
}

const AppProjetosRouteChildren: AppProjetosRouteChildren = {
  AppProjetosProjectIdRoute: AppProjetosProjectIdRoute,
  AppProjetosIndexRoute: AppProjetosIndexRoute,
}

const AppProjetosRouteWithChildren = AppProjetosRoute._addFileChildren(
  AppProjetosRouteChildren,
)

interface AppUnidadesRouteChildren {
  AppUnidadesUnitIdRoute: typeof AppUnidadesUnitIdRoute
  AppUnidadesIndexRoute: typeof AppUnidadesIndexRoute
}

const AppUnidadesRouteChildren: AppUnidadesRouteChildren = {
  AppUnidadesUnitIdRoute: AppUnidadesUnitIdRoute,
  AppUnidadesIndexRoute: AppUnidadesIndexRoute,
}

const AppUnidadesRouteWithChildren = AppUnidadesRoute._addFileChildren(
  AppUnidadesRouteChildren,
)

interface AppRouteChildren {
  AppAdministracaoRoute: typeof AppAdministracaoRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppEquipeRoute: typeof AppEquipeRouteWithChildren
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppPessoasRoute: typeof AppPessoasRouteWithChildren
  AppProjetosRoute: typeof AppProjetosRouteWithChildren
  AppUnidadesRoute: typeof AppUnidadesRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdministracaoRoute: AppAdministracaoRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppEquipeRoute: AppEquipeRouteWithChildren,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppPessoasRoute: AppPessoasRouteWithChildren,
  AppProjetosRoute: AppProjetosRouteWithChildren,
  AppUnidadesRoute: AppUnidadesRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
