/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppAdministracaoRouteImport } from './routes/app/administracao'
import { Route as AppAgendaRouteImport } from './routes/app/agenda'
import { Route as AppDocumentosRouteImport } from './routes/app/documentos'
import { Route as AppFinanceiroRouteImport } from './routes/app/financeiro'
import { Route as AppPessoasRouteImport } from './routes/app/pessoas'
import { Route as AppProjetosRouteImport } from './routes/app/projetos'
import { Route as AppUnidadesRouteImport } from './routes/app/unidades'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AppPessoasIndexRouteImport } from './routes/app/pessoas/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAdministracaoRoute = AppAdministracaoRouteImport.update({
  id: '/administracao',
  path: '/administracao',
  getParentRoute: () => AppRoute,
} as any)
const AppAgendaRoute = AppAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AppRoute,
} as any)
const AppDocumentosRoute = AppDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => AppRoute,
} as any)
const AppFinanceiroRoute = AppFinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => AppRoute,
} as any)
const AppPessoasRoute = AppPessoasRouteImport.update({
  id: '/pessoas',
  path: '/pessoas',
  getParentRoute: () => AppRoute,
} as any)
const AppProjetosRoute = AppProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => AppRoute,
} as any)
const AppUnidadesRoute = AppUnidadesRouteImport.update({
  id: '/unidades',
  path: '/unidades',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPessoasIndexRoute = AppPessoasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppPessoasRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/administracao': typeof AppAdministracaoRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/pessoas': typeof AppPessoasRouteWithChildren
  '/app/projetos': typeof AppProjetosRoute
  '/app/unidades': typeof AppUnidadesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/pessoas/': typeof AppPessoasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/app/administracao': typeof AppAdministracaoRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/projetos': typeof AppProjetosRoute
  '/app/unidades': typeof AppUnidadesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app': typeof AppIndexRoute
  '/app/pessoas': typeof AppPessoasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/app/administracao': typeof AppAdministracaoRoute
  '/app/agenda': typeof AppAgendaRoute
  '/app/documentos': typeof AppDocumentosRoute
  '/app/financeiro': typeof AppFinanceiroRoute
  '/app/pessoas': typeof AppPessoasRouteWithChildren
  '/app/projetos': typeof AppProjetosRoute
  '/app/unidades': typeof AppUnidadesRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/app/': typeof AppIndexRoute
  '/app/pessoas/': typeof AppPessoasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/administracao'
    | '/app/agenda'
    | '/app/documentos'
    | '/app/financeiro'
    | '/app/pessoas'
    | '/app/projetos'
    | '/app/unidades'
    | '/auth/callback'
    | '/app/'
    | '/app/pessoas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/administracao'
    | '/app/agenda'
    | '/app/documentos'
    | '/app/financeiro'
    | '/app/projetos'
    | '/app/unidades'
    | '/auth/callback'
    | '/app'
    | '/app/pessoas'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/login'
    | '/app/administracao'
    | '/app/agenda'
    | '/app/documentos'
    | '/app/financeiro'
    | '/app/pessoas'
    | '/app/projetos'
    | '/app/unidades'
    | '/auth/callback'
    | '/app/'
    | '/app/pessoas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/administracao': {
      id: '/app/administracao'
      path: '/administracao'
      fullPath: '/app/administracao'
      preLoaderRoute: typeof AppAdministracaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/agenda': {
      id: '/app/agenda'
      path: '/agenda'
      fullPath: '/app/agenda'
      preLoaderRoute: typeof AppAgendaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/documentos': {
      id: '/app/documentos'
      path: '/documentos'
      fullPath: '/app/documentos'
      preLoaderRoute: typeof AppDocumentosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/financeiro': {
      id: '/app/financeiro'
      path: '/financeiro'
      fullPath: '/app/financeiro'
      preLoaderRoute: typeof AppFinanceiroRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/pessoas': {
      id: '/app/pessoas'
      path: '/pessoas'
      fullPath: '/app/pessoas'
      preLoaderRoute: typeof AppPessoasRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/projetos': {
      id: '/app/projetos'
      path: '/projetos'
      fullPath: '/app/projetos'
      preLoaderRoute: typeof AppProjetosRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/unidades': {
      id: '/app/unidades'
      path: '/unidades'
      fullPath: '/app/unidades'
      preLoaderRoute: typeof AppUnidadesRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/pessoas/': {
      id: '/app/pessoas/'
      path: '/'
      fullPath: '/app/pessoas/'
      preLoaderRoute: typeof AppPessoasIndexRouteImport
      parentRoute: typeof AppPessoasRoute
    }
  }
}

interface AppPessoasRouteChildren {
  AppPessoasIndexRoute: typeof AppPessoasIndexRoute
}

const AppPessoasRouteChildren: AppPessoasRouteChildren = {
  AppPessoasIndexRoute: AppPessoasIndexRoute,
}

const AppPessoasRouteWithChildren = AppPessoasRoute._addFileChildren(
  AppPessoasRouteChildren,
)

interface AppRouteChildren {
  AppAdministracaoRoute: typeof AppAdministracaoRoute
  AppAgendaRoute: typeof AppAgendaRoute
  AppDocumentosRoute: typeof AppDocumentosRoute
  AppFinanceiroRoute: typeof AppFinanceiroRoute
  AppPessoasRoute: typeof AppPessoasRouteWithChildren
  AppProjetosRoute: typeof AppProjetosRoute
  AppUnidadesRoute: typeof AppUnidadesRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdministracaoRoute: AppAdministracaoRoute,
  AppAgendaRoute: AppAgendaRoute,
  AppDocumentosRoute: AppDocumentosRoute,
  AppFinanceiroRoute: AppFinanceiroRoute,
  AppPessoasRoute: AppPessoasRouteWithChildren,
  AppProjetosRoute: AppProjetosRoute,
  AppUnidadesRoute: AppUnidadesRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthCallbackRoute: AuthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
